questions = [
    {"id": 1, "q": "Which duck breed is known for its crested head?", "options": ["Pekin", "Call", "Crested", "Muscovy"], "answer": 3},
    {"id": 2, "q": "What is a baby duck called?", "options": ["Gosling", "Ducklet", "Duckling", "Chick"], "answer": 3},
    {"id": 3, "q": "Which duck is native to North America?", "options": ["Mandarin", "Muscovy", "Mallard", "Rouen"], "answer": 3},
    {"id": 4, "q": "Ducks often sleep with one eye open to:", "options": ["Detect predators", "Blink less", "Conserve energy", "Look alert"], "answer": 1},
    {"id": 5, "q": "Which part of a duck helps it steer in water?", "options": ["Beak", "Feathers", "Feet", "Tail"], "answer": 4},
    {"id": 6, "q": "What is a male duck called?", "options": ["Hen", "Drake", "Gander", "Cockerel"], "answer": 2},
    {"id": 7, "q": "Which duck breed is used in foie gras production?", "options": ["Pekin", "Muscovy", "Rouen", "Call"], "answer": 2},
    {"id": 8, "q": "What do ducks mostly eat in the wild?", "options": ["Grains", "Insects and aquatic plants", "Cheese", "Fruits"], "answer": 2},
    {"id": 9, "q": "How do ducks keep their feathers waterproof?", "options": ["By shaking off water", "Using preen gland oils", "Brushing them", "Drying in sun"], "answer": 2},
    {"id": 10, "q": "Which duck is known for an upright posture and long legs?", "options": ["Cayuga", "Runner", "Pekin", "Call"], "answer": 2},
    {"id": 11, "q": "Why do ducks bob their heads?", "options": ["To communicate", "To clean feathers", "To stretch", "To balance"], "answer": 1},
    {"id": 12, "q": "Which breed resembles a Mallard but is larger?", "options": ["Crested", "Rouen", "Call", "Buff"], "answer": 2},
    {"id": 13, "q": "What sound is typical of a male duck?", "options": ["Quack", "Squeak", "Raspy croak", "Growl"], "answer": 3},
    {"id": 14, "q": "What is the average lifespan of a wild duck?", "options": ["1–2 years", "3–5 years", "5–10 years", "10–15 years"], "answer": 3},
    {"id": 15, "q": "Which duck breed is notably vocal?", "options": ["Call", "Runner", "Buff", "Rouen"], "answer": 1},
    {"id": 16, "q": "Why do ducks fly in a V-formation?", "options": ["To reduce wind resistance", "To appear orderly", "To follow a leader", "To maintain speed"], "answer": 1},
    {"id": 17, "q": "Ducks belong to which family?", "options": ["Galliformes", "Anatidae", "Aviary", "Poultridae"], "answer": 2},
    {"id": 18, "q": "When do ducks typically molt?", "options": ["Spring", "Summer", "Winter", "Autumn"], "answer": 2},
    {"id": 19, "q": "Which duck breed lays bluish eggs?", "options": ["Khaki Campbell", "Indian Runner", "Magpie", "Swedish"], "answer": 4},
    {"id": 20, "q": "Which of these is not a recognized duck breed?", "options": ["Swedish Blue", "Mandarin", "Polka Dabble", "Call"], "answer": 3},
    {"id": 21, "q": "How many eyelids does a duck have?", "options": ["One", "Two", "Three", "None"], "answer": 3},
    {"id": 22, "q": "Which duck breed is entirely black with an emerald sheen?", "options": ["Cayuga", "Rouen", "Muscovy", "Call"], "answer": 1},
    {"id": 23, "q": "What is a group of ducks in water called?", "options": ["Flock", "Raft", "Team", "Quackpack"], "answer": 2},
    {"id": 24, "q": "What is a group of ducks on land called?", "options": ["Herd", "Pack", "Waddle", "Paddle"], "answer": 3},
    {"id": 25, "q": "What color is a male Mallard’s head?", "options": ["Red", "Blue", "Green", "Yellow"], "answer": 3},
    {"id": 26, "q": "Which duck breed is known for prolific egg-laying?", "options": ["Khaki Campbell", "Pekin", "Cayuga", "Rouen"], "answer": 1},
    {"id": 27, "q": "What is the name of the gland that ducks use to waterproof their feathers?", "options": ["Oil gland", "Preen gland", "Feather gland", "Duck waxer"], "answer": 2},
    {"id": 28, "q": "What does 'dabbling' refer to?", "options": ["Walking in circles", "Head dipping in water", "Sleeping", "Jumping"], "answer": 2},
    {"id": 29, "q": "How do ducks stay warm in cold water?", "options": ["Shiver", "Extra feathers", "Counter‑current heat exchange in legs", "Float more"], "answer": 3},
    {"id": 30, "q": "Which species is especially colorful and kept for ornamental purposes?", "options": ["Pekin", "Mandarin", "Muscovy", "Swedish Blue"], "answer": 2},
    {"id": 31, "q": "Why do ducks wag their tails?", "options": ["To dry off", "When excited", "For balance", "To display"], "answer": 2},
    {"id": 32, "q": "Which duck breed is known for being relatively quiet?", "options": ["Rouen", "Pekin", "Muscovy", "Call"], "answer": 3},
    {"id": 33, "q": "What material composes a duck’s bill?", "options": ["Bone", "Keratin", "Feather", "Cartilage"], "answer": 2},
    {"id": 34, "q": "Can ducks perceive color?", "options": ["Yes", "No", "Only blue", "Only ultraviolet"], "answer": 1},
    {"id": 35, "q": "Which breed has a bluish hue and white bib?", "options": ["Cayuga", "Swedish Blue", "Rouen", "Magpie"], "answer": 2},
    {"id": 36, "q": "How fast can some ducks fly?", "options": ["10 mph", "30 mph", "60 mph", "100 mph"], "answer": 3},
    {"id": 37, "q": "How many toes does a duck have on each foot?", "options": ["2", "3", "4", "5"], "answer": 3},
    {"id": 38, "q": "Which small, domestic breed is popular as a pet?", "options": ["Runner", "Call", "Muscovy", "Pekin"], "answer": 2},
    {"id": 39, "q": "When are ducks most active?", "options": ["Night", "Afternoon", "Morning and evening", "All day"], "answer": 3},
    {"id": 40, "q": "What is unusual about Muscovy ducks?", "options": ["They quack loudly", "They do not quack", "They honk", "They chirp"], "answer": 2},
    {"id": 41, "q": "Which breed is upright and runs quickly?", "options": ["Runner", "Cayuga", "Mallard", "Call"], "answer": 1},
    {"id": 42, "q": "How do ducks clean their feathers?", "options": ["Scratch", "Rub in mud", "Preen with their beak", "Dive"], "answer": 3},
    {"id": 43, "q": "Ducklings imprint on:", "options": ["Their mother", "The first moving object they see", "Their eggshell", "Water"], "answer": 2},
    {"id": 44, "q": "Which part helps a duck steer in water?", "options": ["Beak", "Feet", "Tail", "Wings"], "answer": 3},
    {"id": 45, "q": "Which duck is often mistaken for a goose due to its red face?", "options": ["Pekin", "Muscovy", "Rouen", "Mallard"], "answer": 2},
    {"id": 46, "q": "Ducks belong to which taxonomic family?", "options": ["Galliformes", "Anatidae", "Passeriformes", "Strigidae"], "answer": 2},
    {"id": 47, "q": "Why do ducks often sleep standing on one leg?", "options": ["To conserve body heat", "For posture", "To rest the other leg", "Habit"], "answer": 1},
    {"id": 48, "q": "Duck eggs are usually:", "options": ["White", "Green", "Speckled", "Cream or blue‑green"], "answer": 4},
    {"id": 49, "q": "Which duck breed has a crest of feathers on its head?", "options": ["Crested", "Cayuga", "Runner", "Call"], "answer": 1},
    {"id": 50, "q": "What sound does a male duck typically make?", "options": ["Loud quack", "Hiss", "Low raspy sound", "Whistle"], "answer": 3},
    {"id": 51, "q": "Which duck is commonly featured in Chinese cuisine?", "options": ["Rouen", "Pekin", "Muscovy", "Mandarin"], "answer": 2},
    {"id": 52, "q": "What happens during a duck’s molt?", "options": ["Lays more eggs", "Gains weight", "Sheds and regrows feathers", "Migrates"], "answer": 3},
    {"id": 53, "q": "Where are a duck's nostrils located?", "options": ["Feet", "Under wings", "Top of the bill", "Behind the eyes"], "answer": 3},
    {"id": 54, "q": "What is a baby duck called?", "options": ["Gosling", "Pup", "Duckling", "Chick"], "answer": 3},
    {"id": 55, "q": "Which duck has a black bill and dark emerald feathers?", "options": ["Rouen", "Khaki Campbell", "Cayuga", "Indian Runner"], "answer": 3},
    {"id": 56, "q": "What color are most domesticated Pekin ducks?", "options": ["Brown", "White", "Black", "Grey"], "answer": 2},
    {"id": 57, "q": "Can ducks sleep with one eye open?", "options": ["Yes", "No", "Only in winter", "Only ducklings can"], "answer": 1},
    {"id": 58, "q": "Why do ducks bob their heads?", "options": ["To impress mates", "To check for wind", "To stretch", "They are confused"], "answer": 1},
    {"id": 59, "q": "What is the typical lifespan of a domestic duck?", "options": ["1–2 years", "3–4 years", "5–10 years", "15–20 years"], "answer": 3},
    {"id": 60, "q": "Which duck species is capable of perching in trees?", "options": ["Muscovy", "Pekin", "Rouen", "Khaki Campbell"], "answer": 1},
    {"id": 61, "q": "Which duck breed has a calm temperament and is popular among beginners?", "options": ["Indian Runner", "Pekin", "Call", "Magpie"], "answer": 2},
    {"id": 62, "q": "What is the name for the process where ducks lose and regrow feathers?", "options": ["Shedding", "Molting", "Furling", "Plucking"], "answer": 2},
    {"id": 63, "q": "Which duck breed originated in Germany?", "options": ["Rouen", "Magpie", "Saxony", "Pekin"], "answer": 3},
    {"id": 64, "q": "What helps ducks float on water?", "options": ["Air sacs and hollow bones", "Fat", "Webbed feet", "Muscle density"], "answer": 1},
    {"id": 65, "q": "Which duck breed has striking black and white markings?", "options": ["Magpie", "Call", "Saxony", "Buff"], "answer": 1},
    {"id": 66, "q": "What is a common predator of ducks?", "options": ["Fox", "Rabbit", "Horse", "Swan"], "answer": 1},
    {"id": 67, "q": "What part of a duck’s anatomy allows it to filter food from water?", "options": ["Tongue", "Lamellae", "Nostrils", "Beak edges"], "answer": 2},
    {"id": 68, "q": "How long is the typical incubation period for duck eggs?", "options": ["10 days", "21 days", "28 days", "35 days"], "answer": 3},
    {"id": 69, "q": "Which duck breed is known for being very broody?", "options": ["Call", "Muscovy", "Runner", "Swedish"], "answer": 2},
    {"id": 70, "q": "Which vitamin is essential for a duck’s feather health?", "options": ["Vitamin C", "Vitamin B1", "Vitamin A", "Vitamin D"], "answer": 3},
    {"id": 71, "q": "Ducks’ feet don’t get cold because:", "options": ["They are insulated", "They have poor blood flow", "They have countercurrent circulation", "They’re webbed"], "answer": 3},
    {"id": 72, "q": "Which duck has a white ring around its neck?", "options": ["Mallard", "Pekin", "Khaki Campbell", "Muscovy"], "answer": 1},
    {"id": 73, "q": "How do ducklings learn to swim?", "options": ["By instinct", "By watching siblings", "By being thrown into water", "After a week"], "answer": 1},
    {"id": 74, "q": "What is a female duck called?", "options": ["Hen", "Drake", "Sow", "Doe"], "answer": 1},
    {"id": 75, "q": "Which duck breed has a distinct green sheen?", "options": ["Pekin", "Buff", "Cayuga", "Call"], "answer": 3},
    {"id": 76, "q": "Duck quacks can echo. True or False?", "options": ["True", "False"], "answer": 1},
    {"id": 77, "q": "What time of day do ducks usually feed?", "options": ["Afternoon", "Morning and evening", "Night", "All day"], "answer": 2},
    {"id": 78, "q": "How do ducks communicate?", "options": ["Through quacks and body language", "Only body language", "Via scent", "Through vibrations"], "answer": 1},
    {"id": 79, "q": "Which duck is known for rapid leg movement while running?", "options": ["Crested", "Call", "Runner", "Khaki Campbell"], "answer": 3},
    {"id": 80, "q": "Which duck breed was developed in England for meat production?", "options": ["Khaki Campbell", "Rouen", "Buff Orpington", "Magpie"], "answer": 3},
    {"id": 81, "q": "What color are the feet of most adult Mallard ducks?", "options": ["Yellow", "Black", "Orange", "Pink"], "answer": 3},
    {"id": 82, "q": "Which duck is known for its ability to dive underwater?", "options": ["Pekin", "Muscovy", "Canvasback", "Call"], "answer": 3},
    {"id": 83, "q": "What is the primary function of webbed feet in ducks?", "options": ["Defense", "Digging", "Swimming", "Balancing"], "answer": 3},
    {"id": 84, "q": "Where do wild ducks usually nest?", "options": ["In trees", "On the ground near water", "On cliffs", "Underwater burrows"], "answer": 2},
    {"id": 85, "q": "Which duck breed is known for its distinctive white face?", "options": ["Muscovy", "Buff", "Indian Runner", "Magpie"], "answer": 1},
    {"id": 86, "q": "How do ducks cool themselves in hot weather?", "options": ["Panting", "Sweating", "Gulping water", "Shedding feathers"], "answer": 1},
    {"id": 87, "q": "Which duck is sometimes kept to control insects and weeds?", "options": ["Pekin", "Runner", "Muscovy", "Call"], "answer": 3},
    {"id": 88, "q": "What’s the name of the protective membrane over a duck's eye?", "options": ["Cornea", "Nictitating membrane", "Retina", "Duck lid"], "answer": 2},
    {"id": 89, "q": "Which continent is home to the largest number of duck species?", "options": ["Asia", "Africa", "North America", "Australia"], "answer": 1},
    {"id": 90, "q": "Why do ducks shake their feathers after preening?", "options": ["To show dominance", "To spread oils evenly", "To cool off", "To remove lice"], "answer": 2},
    {"id": 91, "q": "What’s the main difference between diving and dabbling ducks?", "options": ["Color", "Size", "Feeding behavior", "Noise level"], "answer": 3},
    {"id": 92, "q": "Which breed is often confused with geese due to their size?", "options": ["Muscovy", "Buff", "Runner", "Rouen"], "answer": 1},
    {"id": 93, "q": "What time of year do ducks typically migrate?", "options": ["Winter", "Summer", "Spring and Fall", "They don’t migrate"], "answer": 3},
    {"id": 94, "q": "Ducks have how many chambers in their heart?", "options": ["2", "3", "4", "5"], "answer": 3},
    {"id": 95, "q": "What sense is especially strong in ducks?", "options": ["Smell", "Sight", "Hearing", "Touch"], "answer": 2},
    {"id": 96, "q": "What is a common disease affecting ducks?", "options": ["Avian cholera", "Duck rot", "Feather fungus", "Gizzard worms"], "answer": 1},
    {"id": 97, "q": "What’s a unique feature of duck eggs compared to chicken eggs?", "options": ["Smaller yolk", "More protein", "Larger white", "More fat"], "answer": 4},
    {"id": 98, "q": "Which breed is typically used in heritage poultry shows?", "options": ["Pekin", "Saxony", "Rouen", "Call"], "answer": 4},
    {"id": 99, "q": "Which duck has a reputation for being the most independent?", "options": ["Muscovy", "Indian Runner", "Call", "Cayuga"], "answer": 1},
    {"id": 100, "q": "Which duck breed is known for its white plumage and orange bill?", "options": ["Pekin", "Rouen", "Cayuga", "Khaki Campbell"], "answer": 1},
    {"id": 101, "q": "What does it mean when ducks 'dabble' in water?", "options": ["Dive deep", "Tip forward to feed", "Swim backwards", "Shake feathers"], "answer": 2},
    {"id": 102, "q": "Which duck breed has a distinctive knob on its bill?", "options": ["Muscovy", "Call", "Runner", "Pekin"], "answer": 1},
    {"id": 103, "q": "What shape are duck pupils?", "options": ["Round", "Slit", "Horizontal oval", "Vertical oval"], "answer": 3},
    {"id": 104, "q": "Which duck is known for its iridescent green head?", "options": ["Mallard", "Pekin", "Call", "Muscovy"], "answer": 1},
    {"id": 105, "q": "Which sense helps ducks find food underwater?", "options": ["Taste", "Smell", "Sight", "Touch"], "answer": 2},
    {"id": 106, "q": "What is the term for a male duck that cannot reproduce?", "options": ["Barren drake", "Ungainly drake", "Eunuch drake", "Neutered drake"], "answer": 3},
    {"id": 107, "q": "Which duck breed has legs placed farther back on the body?", "options": ["Duck", "Runner", "Call", "Muscovy"], "answer": 2},
    {"id": 108, "q": "Which duck is often used to control slugs and insects in gardens?", "options": ["Call", "Pekin", "Muscovy", "Khaki Campbell"], "answer": 3},
    {"id": 109, "q": "What is the approximate incubation time for duck eggs?", "options": ["21 days", "28 days", "35 days", "42 days"], "answer": 2},
    {"id": 110, "q": "Which duck breed has a white crescent on its face?", "options": ["Magpie", "Crested", "Rouen", "Swedish"], "answer": 1},
    {"id": 111, "q": "What is the typical color of Mallard drake’s chest?", "options": ["Brown", "Black", "White", "Blue"], "answer": 1},
    {"id": 112, "q": "Which duck type nests in cavities like trees?", "options": ["Muscovy", "Mallard", "Pekin", "Call"], "answer": 2},
    {"id": 113, "q": "How often do ducks molt feathers annually?", "options": ["Once", "Twice", "Thrice", "Never"], "answer": 1},
    {"id": 114, "q": "Which duck breed is a hybrid of Mallard and domestic ducks?", "options": ["Muscovy", "Rouen", "Swedish", "Call"], "answer": 2},
    {"id": 115, "q": "What tool helps ducks waterproof their feathers?", "options": ["Beak", "Feet", "Wing", "Preen gland"], "answer": 4},
    {"id": 116, "q": "Which duck breed is feather-footed with tufts?", "options": ["Muscovy", "Cayuga", "Silver Appleyard", "Saxon"], "answer": 4},
    {"id": 117, "q": "How do ducklings regulate their body temperature?", "options": ["Huddling with siblings", "Panting", "Bathing", "Preening"], "answer": 1},
    {"id": 118, "q": "Which duck is known for its calm temperament and often used as therapy animals?", "options": ["Call", "Pekin", "Muscovy", "Khaki Campbell"], "answer": 2},
    {"id": 119, "q": "Ducks have what type of feet?", "options": ["Clawed", "Webbed", "Scaled", "Toeless"], "answer": 2},
]